### ISSUE TITLE
Disable some rule in the SQLDeveloper extension

### ISSUE THREAD

**Issue by himanshu2416** [Trivadis/plsql-cop-sqldev#13]
Hello,
Is there any way to disable G-7310: Avoid standalone procedures – put your procedures in packages rule for my SQLDeveloper.
We have designed our project in a way where we keep most of the procedures standalone.

**Comment by PhilippSalvisberg** [comment]
You can configure that in the preferences:

![image](https://user-images.githubusercontent.com/3883171/126654336-68337283-72af-4828-bb20-1ee7927e812c.png)

You can also exclude checks by severity name or characteristics name as explained in the preferences.

**Comment by pocelka** [comment]
Hello Phillip, 

Is it possible to disable check in-line in the code similar to checkers used by other languages? Skip list is fine, but sometimes it might be better to skip just one occurrence instead of completely ignoring some severity. 

EDIT: 
Seems like I missed that checkbox with NOSONAR. It took mi a while to understand that comment --NOSONAR or --//NOSONAR needs to be on the line reported by extension and not before the statement.

**Comment by PhilippSalvisberg** [comment]
@pocelka Yes, you have to put the `NOSONAR` comment on the line of the reported issue. Then it won't be reported. The use of `NOSONAR` will caused dedicated issues with the number `0`. You may ignore this by adding 0 to the guideline skip list.

The `NOSONAR` comment is a concept introduced by SonarQube. It can be used in other languages as well.

**Comment by PhilippSalvisberg** [comment]
I am closing this issue as I have not heard from @himanshu2416 in over a month.
