### ISSUE TITLE
False positive Issues reported in 'Check' results  pertaininng to  dbms_output.putline(...)

### ISSUE THREAD

**Issue by DavidotNet** [Trivadis/plsql-cop-sqldev#22]
Line | Column | Severity | Characteristics | Message
9 | 34 | 4-Blocker | Reliability | missing ';' at '('
-- | -- | -- | -- | --
9 | 44 | 4-Blocker | Reliability | mismatched input '\|' expecting ';'
9 | 47 | 4-Blocker | Reliability | mismatched input 'char' expecting 'end'
9 | 51 | 4-Blocker | Reliability | no viable alternative at input '('
9 | 52 | 4-Blocker | Reliability | no viable alternative at input '9'
9 | 55 | 4-Blocker | Reliability | no viable alternative at input '\|'

create or replace procedure p_experiment( v_key_in        in  varchar2
                                                                    , b_result_out out boolean)
   authid current_user
is
begin
   raise value_error;
   exception
      when others then
         sys.dbms_output.put_line(v_key_in || char(9) || sqlerrm);   -- Line 9.
end;

**Comment by PhilippSalvisberg** [comment]
The reason for the syntax error is `char(9)` on line 9. Such a function does not exist. While the Oracle Database 23c can compile this procedure without an error (for whatever reason) it will throw a runtime exception. So it does not work. And in this case, it's expected that db* CODECOP throws a `E-0002: Syntax error.`.

If you use `chr(9)` instead of `char(9)` like this:

```sql
create or replace procedure p_experiment( v_key_in     in  varchar2
                                        , b_result_out out boolean)
   authid current_user
is
begin
   raise value_error;
exception
   when others then
      sys.dbms_output.put_line(v_key_in || chr(9) || sqlerrm); -- Line 9.
end;
/
```

db* CODECOP 4.5.0 reports the following issues ordered by severity:

Issue# | Line | Severity | Message | Code Excerpt
-- | -- | -- | -- | --
1 | 6 | Blocker | G-5070: Avoid using Oracle predefined exceptions | raise value_error
2 | 2 | Blocker | G-7330: Always assign values to OUT parameters. | b_result_out
3 | 8 | Critical | G-5040: Avoid use of WHEN OTHERS clause in an exception section without any other specific handlers. | when others then sys.dbms_output.put_line(v_key_in \|\| chr(9) \|\| sqlerrm);
4 | 9 | Critical | G-5080: Always use FORMAT_ERROR_BACKTRACE when using FORMAT_ERROR_STACK or SQLERRM. | sqlerrm
5 | 2 | Major | G-7150: Try to remove unused parameters. | b_result_out out boolean
6 | 1 | Major | G-9108: Always prefix in parameters with 'in_'. | v_key_in in varchar2
7 | 2 | Major | G-9109: Always prefix out parameters with 'out_'. | b_result_out out boolean
8 | 1 | Minor | G-7310: Avoid standalone procedures – put your procedures in packages. | p_experiment
9 | 1 | Minor | G-8310: Always validate input parameter size by assigning the parameter to a size limited variable in the declaration section of program unit. | v_key_in in varchar2

IMO, all reported issues are plausible.

Does this answer your question?

**Comment by DavidotNet** [comment]
**Yes**,  apologies for the 'char' typo.  This matter may be **closed**.
