### ISSUE TITLE
Syntax error when using conditional compilation? (no viable alternative at input '$IF')

### ISSUE THREAD

**Issue by ogobrecht** [Trivadis/plsql-cop-sqldev#4]
Hi Philipp,

thank you for this great tool.

I checked our table API generator with your PLSQL Cop. I get 318 issues marked as blocker but the code compiles successfully. We use conditional compilation - may be this is one of the reasons?

Can you have a look at it? Please check out the [development branch](https://github.com/OraMUC/table-api-generator/tree/development) instead of the master.

Thank you in advance and best regards
Ottmar

Trivadis PL/SQL Cop Version 2.3.2.20200330.100941 for Trivadis PL/SQL & SQL Coding Guidelines Version 3.6

![image](https://user-images.githubusercontent.com/10425445/80811200-b170cf80-8bc5-11ea-8cda-d430cf234173.png)

![image](https://user-images.githubusercontent.com/10425445/80811073-753d6f00-8bc5-11ea-8537-dd6361d40b70.png)

**Comment by PhilippSalvisberg** [comment]
Could you point me to the file please? Thank you.

**Comment by ogobrecht** [comment]
Sorry Philipp,

it is the package body in the src directory: [https://github.com/OraMUC/table-api-generator/blob/development/src/OM_TAPIGEN.pkb](https://github.com/OraMUC/table-api-generator/blob/development/src/OM_TAPIGEN.pkb)

**Comment by ogobrecht** [comment]
For installing the package with the conditional compilation you can either call https://github.com/OraMUC/table-api-generator/blob/development/src/om_tapigen_install.sql or the generated install file https://github.com/OraMUC/table-api-generator/blob/development/om_tapigen_install.sql (here the file references with the @ notation are replaced with the file contents, this is done via a npm build script)

**Comment by PhilippSalvisberg** [comment]
This is a good question.

You are hitting two limitations. Since these are known and documented limitations, we do not plan to fix them. 

However, you can work around the problems with some small adaptions to your code.

I'll explain the issues and show you how to work around it.

## 1. [Quote Delimiter Characters](https://github.com/Trivadis/plsql-cop-cli/blob/master/parser-limitations.md#quote-delimiter-characters)

We have some limitations due to the lexer/parser generator we use behind the scenes. It's not as flexible as RegEx, which is a pity in this case. However, as a compromise we support quote identifiers used by customers of PL/SQL Cop. These are currently the following pairs:

`$$`, `##`, `@@`, `££`, `""`, `||`, `()`, `{}`, `[]`, `<>`, `!!`, `++`, `~~`, `//`.

In your code you are using the pair `^^`. This leads to parsing errors. If you want to use PL/SQL Cop you have to settle for one of the pairs mentioned above.

As a test I replaced all occurrences of `q'^` with `q'£` and all occurrences of `^'`with `£'` to solve the issue. Parsing was possible afterwards.

## 2. [Conditional Compilation](https://github.com/Trivadis/plsql-cop-cli/blob/master/parser-limitations.md#conditional-compilation)

The PL/SQL parser of the Oracle Database handles conditional compilation with the help of a preprocessor. Its result will be parsed. We treat conditional compilation blocks as part of the PL/SQL language. We implemented two variants

- A conditional compilation statement
- A conditional compilation expression

With that we can deal with common conditional compilation code, but not with everything.  

In your case the conditional compilation blocks are not recognized as expressions. Here's a simplified excerpt of your code:

```sql
SELECT $IF $$db_version < 121 $THEN
          'N' AS default_on_null_yn,
       $ELSE
          CASE WHEN default_on_null = 'YES' THEN 'Y' ELSE 'N' END AS default_on_null_yn,
       $END
       CASE
          WHEN column_name_nn IS NOT NULL THEN
             'N'
          ELSE
             'Y'
       END AS is_nullable_yn,
       virtual_column
 FROM all_tab_cols;
```
The `$IF` ... `$END` block is not recognized as a SQL expression. For example, if you replace it with a simple expression such as `'N'`, then you see that the resulting SQL statement is incomplete. That's why our parser throws a parse error. 

In this case it is easy to fix. If you rewrite the code as follows:

```sql
SELECT $IF $$db_version < 121 $THEN
          'N'
       $ELSE
          CASE WHEN default_on_null = 'YES' THEN 'Y' ELSE 'N' END
       $END AS default_on_null_yn,
       CASE
          WHEN column_name_nn IS NOT NULL THEN
             'N'
          ELSE
             'Y'
       END AS is_nullable_yn,
       virtual_column
 FROM all_tab_cols;
```

Now the `$IF` ... `$END` block is recognized as a SQL expression with a column name `is_nullable_yn`. That works with our parser.

But there is another problem in your code. It's the named query `identity_columns` as part of the subquery_factorying_clause. 

```sql
    identity_columns AS
     ($IF $$db_version < 121 $THEN
      SELECT 'DUMMY_COLUMN_NAME' AS column_name_identity,
              NULL AS identity_type
        FROM dual
      $ELSE
      SELECT column_name AS column_name_identity,
             generation_type AS identity_type
        FROM all_tab_identity_cols
       WHERE owner = g_params.owner
         AND table_name = g_params.table_name
      $END),
```

It is completely different depending on the Oracle version. The `$IF` ... `$END` block does not represent a SQL expression. In this case I do not see an easy way to fix it. You might think that you could provide a subquery incl. the braces as the SQL expression, but it does not work, because the grammar is defined differently.

You can solve it, if you put the complete cursor into a conditional block. One branch for `$$db_version < 121` and one branch for the else case. I've put the [solution in a Gist](https://gist.github.com/PhilippSalvisberg/65532b3131a0a272db42049542051518#file-om_tapigen-sql-L178-L367). I know this solution is not that sexy since it contains a lot of repetitive code. Of course there are other solutions, but this would involve processing logic changes and I tried to avoid that. An advantage of this approach is, that the queries in the branches are easier to test.

After these changes I successfully analyzed the code with PL/SQL Cop. These critical issues were reported:

![image](https://user-images.githubusercontent.com/3883171/80860688-99eb2280-8c69-11ea-91a1-9fc200ca2987.png)

**Comment by ogobrecht** [comment]
Hi Philipp,

it looks like I should have taken a deeper look into the available documentation instead of contacting you. Thank you very much for taking the trouble to point out the problems and solve them right away! THANK YOU.

I hope your answer is helpful for future problems of other users - a nice side effect here on GitHub.

Once again, many thanks for the detailed answer.

Best regards from Munich
Ottmar

**Comment by PhilippSalvisberg** [comment]
You're very welcome, Ottmar. Please do not hesitate to open an issue if you encounter a problem. It shows how the stuff is used. It might also lead to rethinking certain limitations. I was happy to help. Philipp
