### ISSUE TITLE
Syntax not parsed correctly with APEX_ESCAPE

### ISSUE THREAD

**Issue by S-Koell** [Trivadis/plsql-cop-sqldev#6]
I dont know if this should be posted in this repo or in the CLI but I settled up here because I'm using the SQL Dev version.

The following code is not parsed correctly I assume:

```
declare
   co_scale_unset_target_weight  VARCHAR2(100)  := 'abc' || apex_escape.json(' 0 "" ""'); 
begin
    null;
end;
/
```

I get multiple Issues here:

```
2 | 76 | 4-Blocker | Reliability | mismatched input '|' expecting ';'
-- | -- | -- | -- | --
2 | 79 | 4-Blocker | Reliability | no viable alternative at input '.'
2 | 95 | 4-Blocker | Reliability | missing 'begin' at '('
6 | 1 | 4-Blocker | Reliability | missing 'end' at '/'
```

**Comment by PhilippSalvisberg** [comment]
Thanks Sebastian for reporting this. This repo is ok. 

This issue has been reported by e-mail in September. This is a known limitation (see see also https://github.com/Trivadis/plsql-cop-cli/blob/main/parser-limitations.md, `JSON` is a keyword). However, since this is a popular APEX package we added it to our JIRA system (PLSQLCOP-287) and is fixed on our develop branch. It will be part of version 3.0, which should be released very soon.

As a short-term workaround you can use a quoted identifier. This works always. Here's a working example with the current version of PL/SQL Cop:

```sql
declare
   co_scale_unset_target_weight  VARCHAR2(100)  := 'abc' || apex_escape."JSON"(' 0 "" ""'); 
begin
    null;
end;
/
```

HTH.

**Comment by S-Koell** [comment]
Thanks for the quick reply!
