### ISSUE TITLE
G-2410 is wrongly reported in some cases

### ISSUE THREAD

**Issue by deboiph** [Trivadis/plsql-cop-sqldev#9]
Rule G-2410 (Try to use boolean data type for values with dual meaning) is wrongly reported as violated for the following PL/SQL code:

   procedure test
   is
      l_step integer;
   begin
      l_step := 1;
      -- ...
      l_step := 2;
      -- ...
      <<myloop>>
      for i in 3..10 loop
         l_step := l_step + 1;
      end loop myloop;
   end test;

The check seems to be based on the assignment of constant values only. When a non-constant expression is assigned to a variable, this latest should not be considered as having a dual meaning.

The above code is a bit silly but it has been written just for the purpose of reporting this issue.

[deboiph.zip](https://github.com/Trivadis/plsql-cop-sqldev/files/6130741/deboiph.zip)

**Comment by PhilippSalvisberg** [comment]
Yes that's a false positive. It's not possible to avoid that. For example when you reading data from a table into `l_step`. 

In this particular case it would be technically possible to recognize that `l_step` can have more than two values. However, I'm not sure if it is worth the effort to implement that, because there are a lot of other cases where it is not possible (e.g. when the bounds are variables).

I see the following options:

- Disable the rule
- Use the `-- NOSONAR` comment to disable the false positive
- Mark the false positives in SonarQube so that it will not be reported on subsequent runs

Would that be an option for you?

**Comment by PhilippSalvisberg** [comment]
see also https://github.com/Trivadis/plsql-cop-cli/blob/main/validator-limitations.md#g-2410-try-to-use-boolean-data-type-for-values-with-dual-meaning

**Comment by deboiph** [comment]
You are right, it's not worth the effort to implement a more complex check.
I can leave with it and just ignore this false positive.
Does the --NOSONAR tag also works within PL/SQL Developer? I doubt.
Would you have a link to a page where the functioning of this tag is described?
I don't know where it should be put and its scope (entire package?).

**Comment by PhilippSalvisberg** [comment]
> Does the --NOSONAR tag also works within PL/SQL Developer? 

You mean SQL Developer? Yes. It works there as well.

**Comment by PhilippSalvisberg** [comment]
> I don't know where it should be put and its scope (entire package?).

The scope of the "--NOSONAR" marker is always a line. You have to put it on the with the violation.

**Comment by PhilippSalvisberg** [comment]
> Would you have a link to a page where the functioning of this tag is described?

It's the implementation of a SonarQube concept. It's documented here: https://docs.sonarqube.org/latest/faq/

**Comment by PhilippSalvisberg** [comment]
Here's your adapted example:

```sql
create procedure test is
   l_step integer; -- NOSONAR: no dual meaning
begin
   l_step  := 1;
   l_step  := 2;
   for i in 3..10 loop
      l_step := l_step + 1;
   end loop myloop;
end test;
/
```

**Comment by deboiph** [comment]
Thanks for your reply.
